export enum TokenKind {
  LeftParen = 'LeftParen',
  RightParen = 'RightParen',
  LeftBrace = 'LeftBrace',
  RightBrace = 'RightBrace',
  Comma = 'Comma',
  Dot = 'Dot',
  Minus = 'Minus',
  Plus = 'Plus',
  Semicolon = 'Semicolon',
  Slash = 'Slash',
  Star = 'Star',

  Bang = 'Bang',
  Ne = 'Ne',
  Eq = 'Eq',
  EqEq = 'EqEq',
  Gt = 'Gt',
  Ge = 'Ge',
  Lt = 'Lt',
  Le = 'Le',

  Identifier = 'Identifier',
  String = 'String',
  Number = 'Number',

  And = 'And',
  Class = 'Class',
  Else = 'Else',
  False = 'False',
  Fn = 'Fn',
  For = 'For',
  If = 'If',
  None = 'None',
  Or = 'Or',
  Print = 'Print',
  Return = 'Return',
  Super = 'Super',
  This = 'This',
  True = 'True',
  Var = 'Var',
  While = 'While',

  Eof = 'Eof',
}
